-- 구조 파악
DESCRIBE EMPLOYEES; -- 

-- 1. EMPLOYEES 테이블에서 FIRST_NAME, LAST_NAME 조회하기
SELECT E.FIRST_NAME, E.LAST_NAME -- 칼럼에서는 AS로 별명 부여 가능 테이블은 안됨
  FROM HR.EMPLOYEES;
  
-- 2. EMPLOYEES 테이블에서 DEPARTMENT_ID를 중복 제거하고 조회하기
SELECT DISTINCT DEPARTMENT_ID
  FROM EMPLOYEES;
  
-- 3. EMPLOYEE 테이블에서 EMPLOYEE_ID가 150인 사원 조회하기
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME
  FROM EMPLOYEES
 WHERE EMPLOYEE_ID = 150; -- WHERE절(조건)의 등호는(=)는 비교 연산자
 
-- 4. EMPLOYEES 테이블에서 SALARY가 10000 ~ 20000 사이인 사원 조회하기
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY
  FROM EMPLOYEES
 WHERE SALARY BETWEEN 10000 AND 20000;

-- 5. EMPLOYEES 테이블에서 DEPARTMENT_ID가 30, 40, 50인 사원 조회하기
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE DEPARTMENT_ID IN(30, 40, 50);
 
-- 6. EMPLOYEES 테이블에서 DEPARTMENT_ID가 NULL 사원 조회하기
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE DEPARTMENT_ID IS NULL; -- 널 조회는 IS NULL로, IS NOT NULL
 
-- 7. EMPLOYEES 테이블에서 PHONE_NUMBER가 '515' 로 시작하는 사원 조회하기
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, PHONE_NUMBER
  FROM EMPLOYEES
 WHERE PHONE_NUMBER LIKE '515%'; -- 와일드카드 사용은 LIKE 연산자 사용 515시작 하지 않는 것은 NOT LIKE '515%'
 
-- 8. EMPLOYEES 테이블을 FIRST_NAME의 가나다순(오름차순:Ascending Sort)으로 정렬해서 조회하기
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME
  FROM EMPLOYEES
 ORDER BY FIRST_NAME ASC;   -- ASC는 생략 가능하다.

-- 9. EMPLOYEES 테이블을 높은 SALARY(내림차순:Descending Sort)를 받는 사원순으로 먼저 조회하기
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY
  FROM EMPLOYEES
 ORDER BY SALARY DESC;   -- DESC는 생략이 불가능하다.
 
-- 10. EMPLOYEES 테이블의 사원들을 DEPARTMENT_ID 순으로 조회하고, 동일한 DEPARTMENT_ID를 가진 사원들은 높은 SALARY 순으로 조회하기
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME,DEPARTMENT_ID, SALARY
  FROM EMPLOYEES
 ORDER BY DEPARTMENT_ID ASC, SALARY DESC;