DROP TABLE 수강신청_TBL;
DROP TABLE 과목_TBL;
DROP TABLE 학생_TBL;


CREATE TABLE 학생_TBL(
    학번 VARCHAR2(5 BYTE) NOT NULL,
    성명 VARCHAR2(15 BYTE) NULL,
    나이 NUMBER(3) NULL,
    CONSTRAINT PK_학생 PRIMARY KEY(학번)
);
CREATE TABLE 과목_TBL(
    과목코드 VARCHAR2(2 BYTE) NOT NULL,
      과목명 VARCHAR2(10 BYTE),
      교수명 VARCHAR2(10 BYTE),
    CONSTRAINT PK_과머목 PRIMARY KEY(과목코드)
);
CREATE TABLE 수강신청_TBL(
    신청번호 NUMBER NOT NULL,
        학번 VARCHAR2(5 BYTE),
    과목코드 VARCHAR2(2 BYTE),
    CONSTRAINT PK_수강 PRIMARY KEY(신청번호),
    CONSTRAINT FK_수강_학생 FOREIGN KEY(학번) REFERENCES 학생_TBL(학번),
    CONSTRAINT FK_수강_과목 FOREIGN KEY(과목코드) REFERENCES 과목_TBL(과목코드)
);

